### PR TITLE
Expose programmatic API via main in package.json

### PR DESCRIPTION
**Pull request by perrin4869**
Solves https://github.com/fontello/ttf2eot/issues/4

### CODE REVIEW

**Comment by puzrin** [comment]
Sorry, no. I don't like to place kluges here. You need to implement a proper resolver at your side, if you don't like to use `require()` directly. For example, with `require.resolve()` or with https://www.npmjs.com/package/resolve

**Comment by perrin4869** [comment]
Can you explain why this is a kluge? It seems like a perfectly good solution to me. I don't see any other good way of importing the function `ttf2eof`, which is exported by `index.js`...

The only workaround I see is to use `require('ttf2eot/index.js')`, but that is very brittle, if in the future you move the content of `index.js` elsewhere it would break our script...

**Comment by puzrin** [comment]
`require('ttf2eot')` resolves to index.js properly. See https://nodejs.org/api/modules.html#modules_all_together

**Comment by perrin4869** [comment]
ohhh, right! Sorry, my bad!

**Pull request closed without merging**
